import { Navbar } from "@/components/features/layout/navbar";
import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import { Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

// Heading font - Using Montserrat from Google Fonts
export const headingFont = Playfair_Display({
  subsets: ["latin"],
  display: "swap", // Use 'swap' to ensure text is visible during font loading
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Suppress hydration warning used for next-thems
    // https://ui.shadcn.com/docs/dark-mode/next
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${headingFont.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
