name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup latest version of Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build
