name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup latest version of Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - run: npm run eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup latest version of Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - run: |
        if ! npm run prettier; then
          echo "::error ::Style issues found, run 'npm run prettier:fix'" && exit 1
        fi
